import re
from datetime import datetime
from fpdf import FPDF
from fpdf.enums import XPos, YPos


# ── helpers ──────────────────────────────────────────────────────────────────

def _clean(text: str) -> str:
    """Strip markdown syntax and force latin-1 safe chars."""
    text = re.sub(r'\*\*(.+?)\*\*', r'\1', text)
    text = re.sub(r'\*(.+?)\*', r'\1', text)
    text = re.sub(r'#{1,6}\s*', '', text)
    text = re.sub(r'`(.+?)`', r'\1', text)
    text = text.replace('•', '-').replace('’', "'").replace('‘', "'")
    text = text.replace('“', '"').replace('”', '"').replace('–', '-').replace('—', '-')
    return text.encode('latin-1', errors='replace').decode('latin-1')


BLUE = (30, 64, 175)
LIGHT_BLUE = (239, 246, 255)
DARK = (30, 30, 30)
GRAY = (100, 100, 100)


# ── PDF class ────────────────────────────────────────────────────────────────

class StrategyReport(FPDF):
    def header(self):
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(*GRAY)
        self.cell(
            0, 8,
            'AI Product Strategy Assistant  |  Confidential',
            align='R',
            new_x=XPos.LMARGIN, new_y=YPos.NEXT,
        )
        self.set_text_color(*DARK)

    def footer(self):
        self.set_y(-14)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(*GRAY)
        self.cell(
            0, 8,
            f'Page {self.page_no()}  |  Generated {datetime.now().strftime("%B %d, %Y")}',
            align='C',
        )
        self.set_text_color(*DARK)


# ── public function ──────────────────────────────────────────────────────────

def generate_pdf(agent_results: dict, summary: dict) -> bytes:
    pdf = StrategyReport()
    pdf.set_auto_page_break(auto=True, margin=18)

    # ── Cover page ────────────────────────────────────────────────────────────
    pdf.add_page()

    # Blue banner
    pdf.set_fill_color(*BLUE)
    pdf.rect(0, 0, 210, 70, 'F')

    pdf.set_y(14)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Helvetica', 'B', 26)
    pdf.cell(0, 14, 'Product Strategy Report', align='C', new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font('Helvetica', '', 13)
    pdf.cell(0, 8, 'AI-Powered Multi-Agent Analysis', align='C', new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(0, 7, datetime.now().strftime('%B %d, %Y'), align='C', new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # Key metrics box
    pdf.set_y(80)
    pdf.set_text_color(*DARK)
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 8, 'KEY METRICS', new_x=XPos.LMARGIN, new_y=YPos.NEXT)
    pdf.set_font('Helvetica', '', 11)

    metrics = [
        f"Total Revenue       :  ${summary['total_revenue']:,.2f}",
        f"Total Profit        :  ${summary['total_profit']:,.2f}",
        f"Profit Margin       :  {summary['profit_margin']:.1f}%",
        f"Total Units Sold    :  {summary['total_units']:,}",
        f"Avg Customer Rating :  {summary['avg_rating']:.2f} / 5.0",
        f"Total Returns       :  {summary['total_returns']:,}",
    ]
    for m in metrics:
        pdf.cell(0, 7, m, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    # ── Agent sections ────────────────────────────────────────────────────────
    sections = [
        ('data_analysis',         'Data Analysis',          'Data Analysis Agent'),
        ('customer_feedback',     'Customer Insights',      'Customer Feedback Agent'),
        ('market_opportunity',    'Market Opportunities',   'Market Opportunity Agent'),
        ('swot',                  'SWOT Analysis',          'SWOT Analysis Agent'),
        ('feature_prioritization','Feature Prioritization', 'Feature Prioritization Agent'),
        ('opportunity_scoring',   'Opportunity Scores',     'Opportunity Scoring Agent'),
        ('roadmap',               'Product Roadmap',        'Roadmap Generation Agent'),
        ('executive_summary',     'Executive Summary',      'Executive Report Agent'),
    ]

    for key, title, agent_name in sections:
        content = agent_results.get(key, '')
        if not content:
            continue

        pdf.add_page()

        # Section header bar
        pdf.set_fill_color(*BLUE)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font('Helvetica', 'B', 14)
        pdf.cell(
            0, 12, f'  {title}',
            fill=True, new_x=XPos.LMARGIN, new_y=YPos.NEXT,
        )
        pdf.set_font('Helvetica', 'I', 9)
        pdf.set_text_color(*GRAY)
        pdf.cell(
            0, 6, f'  Generated by {agent_name}',
            new_x=XPos.LMARGIN, new_y=YPos.NEXT,
        )
        pdf.ln(3)

        # Render content line by line
        for line in content.split('\n'):
            raw = line.strip()
            if not raw:
                pdf.ln(2)
                continue

            clean = _clean(raw)

            if raw.startswith('## ') or raw.startswith('# '):
                pdf.set_font('Helvetica', 'B', 11)
                pdf.set_text_color(*BLUE)
                pdf.multi_cell(0, 7, clean, new_x=XPos.LMARGIN, new_y=YPos.NEXT)
                pdf.set_text_color(*DARK)

            elif raw.startswith('### '):
                pdf.set_font('Helvetica', 'B', 10)
                pdf.set_text_color(*DARK)
                pdf.multi_cell(0, 6, clean, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

            elif raw.startswith(('- ', '* ', '• ')):
                pdf.set_font('Helvetica', '', 10)
                pdf.set_text_color(50, 50, 50)
                pdf.multi_cell(0, 6, f'  {clean}', new_x=XPos.LMARGIN, new_y=YPos.NEXT)

            elif re.match(r'^\d+\.', raw):
                pdf.set_font('Helvetica', '', 10)
                pdf.set_text_color(50, 50, 50)
                pdf.multi_cell(0, 6, f'  {clean}', new_x=XPos.LMARGIN, new_y=YPos.NEXT)

            else:
                pdf.set_font('Helvetica', '', 10)
                pdf.set_text_color(50, 50, 50)
                pdf.multi_cell(0, 6, clean, new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    return bytes(pdf.output())
